require('globals')

require('my') -- my plugins

require('plugins').setup()
require('plugins.comment')
require('plugins.projection')
require('plugins.notification')
require('plugins.tabline')
require('plugins.git')
require('plugins.filetree')
require('plugins.terminal-handler')
require('plugins.test-runner')
require('plugins.fuzzyfinder')
require('plugins.treesitter')
require('plugins.completion')
require('plugins.lsp')
require('plugins.debugger')
require('plugins.statusline')
require('plugins.floating_identifier')
require('plugins.todo')
require('plugins.highlight')
require('plugins.restorer')
