#!/bin/bash

old_path="$PWD"
ruby_version="$(rbenv version-name)"
force_upgrade="$1"
rbenv global system
rbenv rehash

config_opts="--enable-gui=no \
  --without-x \
  --enable-multibyte \
  --with-tlib=ncurses \
  --enable-cscope \
  --with-features=huge \
  --enable-pythoninterp \
  --enable-rubyinterp"

if [[ $(uname) == 'Darwin' ]]
then
  vim_src_path="/Library/Caches/Homebrew/vim--hg"
  prefix="/usr/local/Cellar/vim/HEAD"
  config_opts="$config_opts --prefix=$prefix --mandir=/usr/local/Cellar/vim/HEAD/share/man"
  make_install_opts="prefix=$prefix STRIP=/usr/bin/true"
else
  vim_src_path="/opt/vim"
  prefix="/usr/local"
  config_opts="$config_opts --prefix=$prefix"
  make_install_opts="prefix=$prefix"
fi

local_tags="$vim_src_path/.hgtags"
remote_tags="/tmp/vim-tags"

clone() {
  sudo mkdir -p $vim_src_path
  sudo chmod 777 $vim_src_path
  cd $vim_src_path
  hg clone https://vim.googlecode.com/hg/ .
}

update() {
  cd $vim_src_path
  hg pull
  hg update
}

hasChanges() {
  curl -s https://vim.googlecode.com/hg/.hgtags > $remote_tags
  if [[ -z "$(diff $remote_tags $local_tags)" && -z $force_upgrade ]]
  then
    echo "nothing to do"
    return -1
  else
    return 0
  fi
}

compile() {
  cd src
  make clean
  make distclean
  ./configure $config_opts
  make
  sudo make install $make_install_opts
  vim --version
}

if [[ ! -d $vim_src_path ]]
then
  clone
  compile
else
  if hasChanges
  then
    update
    compile
  fi
fi

cd $old_path
rbenv global $ruby_version
rbenv rehash
