set statusline=
set statusline+=[%n]
set statusline+=%t%m
set statusline+=%=
set statusline+=%r%y
set statusline+=[%{&ff}]
set statusline+=[%{&fenc!=''?&fenc:&enc}]
set statusline+=[%c,%l/%L]
set laststatus=2
